name = "id"
main = "bot.py"
compatibility_date = "2024-04-01"

# 这里的 [python_workers] 必须加 s，且明确列出所有包
[python_workers]
packages = ["fastapi", "pyodide-http", "requests"]

[observability]
enabled = true
